import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        // Optional native deps of `ws` — loaded via try/catch in the Node mqtt build.
        "bufferutil",
        "utf-8-validate",
    ],
    format: "cjs",
    target: "es2020",
    // "node" so esbuild keeps Node built-ins (net/tls/...) as runtime requires for the
    // desktop TCP path (Electron provides them). The WebSocket build is imported via an
    // explicit subpath and the Node build is only require()'d lazily on desktop, so mobile
    // never touches Node built-ins. See src/mqtt/load-client.ts.
    platform: "node",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
